### PR TITLE
Feature/styling brushup

### PR DESCRIPTION
**Pull request by berachele**
# Description
Created LESS folder and files with variables and mixins and current styling css folders (translated into less). Also rerouted the imports so that deploy renders correctly. Laid out comments for color scheme and fonts--will start implementing and importing fonts and make styling changes. Also created a favicon to replace the waffle in the Tab to fit the Citrics. 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Change Status
- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [x] Incomplete/work-in-progress, PR is for discussion/feedback
## Has This Been Tested
- [ ] Yes
- [x] No
- [ ] Not necessary
## Does this require communication between DS and WEB?
- [ ] Yes, and I have already reached out to someone
- [ ] Yes, but I still need to reach out to someone
- [x] No
## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least two peers
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by alanblee — CHANGES_REQUESTED** [review]
So instead of importing each of the less files per component. You can import the index.less straight into the root component (index.js) where the <App /> lives and it should give all the styling to all the components.

**Review by ddhorstman — APPROVED** [review]
Glad you figured out the import issue!

**Review by alanblee — APPROVED** [review]
Nice job figuring out the imports!

**Comment by Bhavani-Rajan** [comment]
looks good

**Pull request merged**
